ALTER TABLE utilisateurs
  ADD COLUMN actif TINYINT(1) NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS annonces (
  id INT(11) NOT NULL AUTO_INCREMENT,
  titre VARCHAR(255) NOT NULL,
  contenu TEXT NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  statut VARCHAR(50) NOT NULL DEFAULT 'En attente',
  date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS messages_contact (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  nom VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  sujet VARCHAR(255) DEFAULT NULL,
  message TEXT NOT NULL,
  lu TINYINT(1) NOT NULL DEFAULT 0,
  date_message TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY user_id (user_id),
  CONSTRAINT messages_contact_ibfk_1 FOREIGN KEY (user_id) REFERENCES utilisateurs (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
